services:
  - type: web
    name: murmur-backend
    env: python
    rootDir: backend_server
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
